import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Elements } from '@stripe/react-stripe-js';
import { loadStripe, StripeElementsOptions } from '@stripe/stripe-js';
import StripeProvider from '~/context/stripe';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const options: StripeElementsOptions = {
    mode: 'setup',
    currency: 'usd',
    // Fully customizable with appearance API.
    appearance: {},
  };

  const stripePromise = loadStripe(
    'pk_test_51NWbEnG3GvT31NaVIQqD5PrgevW9GBH5e8UAy2sFzMcSCVWXgDyEBA3eZfFPUriP7G3HI3y45FW8rCBi5xWp1T0800NYx01H9c'
  );
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
